
[functions.create_dummy_submission]
enabled = true
verify_jwt = true
import_map = "./functions/create_dummy_submission/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create_dummy_submission/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create_dummy_submission/*.html" ]
