[functions.create_dummy_submission]
enabled = true
verify_jwt = false
import_map = "./functions/create_dummy_submission/deno.json"
entrypoint = "./functions/create_dummy_submission/index.ts"

[functions.ping]
enabled = true
verify_jwt = false
entrypoint = "./functions/ping/index.ts"

[functions.get_random_puzzle]
enabled = true
verify_jwt = false
entrypoint = "./functions/get_random_puzzle/index.ts"

[functions.get_daily_puzzle]
enabled = true
verify_jwt = false
entrypoint = "./functions/get_daily_puzzle/index.ts"
